package net.azureaaron.mod.util;

import java.util.Arrays;
import java.util.List;

import net.minecraft.component.DataComponentTypes;
import net.minecraft.component.type.AttributeModifiersComponent;
import net.minecraft.component.type.LoreComponent;
import net.minecraft.component.type.NbtComponent;
import net.minecraft.datafixer.fix.ItemIdFix;
import net.minecraft.datafixer.fix.ItemInstanceTheFlatteningFix;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NbtCompound;
import net.minecraft.registry.Registries;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class ItemUtils {

	public static ItemStack createStack(Identifier id, Text name, Text[] lore, NbtCompound extraAttributes) {
		ItemStack stack = new ItemStack(Registries.ITEM.get(id));
		NbtCompound customData = new NbtCompound();

		//Copy extra attributes
		customData.put("ExtraAttributes", extraAttributes);
		stack.set(DataComponentTypes.CUSTOM_DATA, NbtComponent.of(customData));

		//Add the lore and name to the item stack
		stack.set(DataComponentTypes.CUSTOM_NAME, name);
		stack.set(DataComponentTypes.LORE, new LoreComponent(Arrays.asList(lore)));

		//Hide useless item modifiers
		stack.set(DataComponentTypes.ATTRIBUTE_MODIFIERS, new AttributeModifiersComponent(List.of(), false));

		//Allows the mod to identify this as being generated by it so it can work with the sb stuff
		stack.setAlwaysDisplaySkyblockInfo(true);

		return stack;
	}

	public static Identifier identifierFromOldId(int id, int damage) {
		return damage != 0 ? new Identifier(ItemInstanceTheFlatteningFix.getItem(ItemIdFix.fromId(id), damage)) : new Identifier(ItemIdFix.fromId(id));
	}
}
